In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("/Users/shubamsarawagi/Downloads/student_extended_ml_dataset2.csv")

In [10]:
df

Name  Age  Gender  Hours_Studied   IQ  Physics_Marks  \
0            Jason Vargas   19    Male       8.140821   92             87   
1          Sandra Wiggins   35  Female       9.825626  112             86   
2             Julia Olsen   33    Male       8.835372  131             87   
3       Robert Pennington   33    Male       2.482483  138             70   
4           Kayla Sellers   28  Female       4.419793   90             95   
...                   ...  ...     ...            ...  ...            ...   
4995         Steven Lynch   30  Female       3.653474  143             93   
4996       Donna Hamilton   33  Female       1.096493  132             68   
4997   Mrs. Ashley Howard   38    Male       4.156770  111             76   
4998        Kendra Murray   18  Female       6.788548  137             81   
4999  Christine Rodriguez   38    Male       1.627111   95             52   

      Math_Marks  Chemistry_Marks  Has_Part_Time_Job Study_Hours_Group  
0             43               85               True              High  
1             81               54              False              High  
2             52               57               True              High  
3             86               83              False               Low  
4             48               83               True               Low  
...          ...              ...                ...               ...  
4995          59               85               True               Low  
4996          70               99               True               Low  
4997          96               71              False               Low  
4998          98               73              False              High  
4999          70               74               True               Low  

[5000 rows x 10 columns]

In [11]:
x = df.drop(columns = ["Name", "Study_Hours_Group"]).values
x.reshape(-1,8)

array([[19, 'Male', 8.14082056496224, ..., 43, 85, True],
       [35, 'Female', 9.825626474274308, ..., 81, 54, False],
       [33, 'Male', 8.83537190109577, ..., 52, 57, True],
       ...,
       [38, 'Male', 4.156769692024423, ..., 96, 71, False],
       [18, 'Female', 6.7885484160694505, ..., 98, 73, False],
       [38, 'Male', 1.6271114840414964, ..., 70, 74, True]], dtype=object)

In [12]:
y = df[["Study_Hours_Group"]].values
y.reshape(-1,1).ravel()

array(['High', 'High', 'High', ..., 'Low', 'High', 'Low'], dtype=object)

In [13]:
missValSum = df.isnull().sum()
missValSum

Name                 0
Age                  0
Gender               0
Hours_Studied        0
IQ                   0
Physics_Marks        0
Math_Marks           0
Chemistry_Marks      0
Has_Part_Time_Job    0
Study_Hours_Group    0
dtype: int64

In [14]:
from sklearn.preprocessing import OrdinalEncoder
ordEnc = OrdinalEncoder()

x[:, [1, 7]] = ordEnc.fit_transform(x[:, [1, 7]])
x

array([[19, 1.0, 8.14082056496224, ..., 43, 85, 1.0],
       [35, 0.0, 9.825626474274308, ..., 81, 54, 0.0],
       [33, 1.0, 8.83537190109577, ..., 52, 57, 1.0],
       ...,
       [38, 1.0, 4.156769692024423, ..., 96, 71, 0.0],
       [18, 0.0, 6.7885484160694505, ..., 98, 73, 0.0],
       [38, 1.0, 1.6271114840414964, ..., 70, 74, 1.0]], dtype=object)

In [15]:
from sklearn import preprocessing
x = preprocessing.MinMaxScaler().fit_transform(x)

In [16]:
from sklearn.preprocessing import LabelEncoder
labelEnc = LabelEncoder()
y = labelEnc.fit_transform(y).reshape(-1,1).ravel()
y

/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, ..., 1, 0, 1])

In [17]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [18]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [19]:
model.score(x_test, y_test)

0.7433949022178733

In [20]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(max_iter=1000)
logreg.fit(x_train, y_train)


LogisticRegression(max_iter=1000)

In [21]:
logreg.score(x_test,y_test)

0.998

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

logreg = LogisticRegression(max_iter=1000)
scores = cross_val_score(logreg, x, y, cv=10)

print("Cross-validation scores:", scores)
print("Mean cross-validation score:", scores.mean())

Cross-validation scores: [0.994 0.996 1.    0.996 0.994 0.998 0.996 0.996 1.    1.   ]
Mean cross-validation score: 0.9969999999999999


In [23]:
from sklearn.neighbors import KNeighborsClassifier
accuracy_scores = []
k_values = []
for k in range(1, 100):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_train,y_train)
    
    accuracy = knn.score(x_test, y_test)
    
    accuracy_scores.append(accuracy)
    k_values.append(k)

optimal_k = k_values[np.argmax(accuracy_scores)]
print("Optimal k without cross-validation:", optimal_k)

Optimal k without cross-validation: 70


In [24]:
knn = KNeighborsClassifier(n_neighbors=70)
model_1=knn.fit(x_train,y_train)
model_1.score(x_test, y_test)

0.973